### ISSUE TITLE
New Term Requests : NARMS, NCCLS

### ISSUE THREAD

**Issue by Anoosha-Sehar** [arpcard/aro#10]
Dear ARO curators,
My name is Anoosha. I would like to submit a request, to add a couple of terms to the ARO ontology. I need these terms as a part of the AMR-GRDI project I'm currently working on. Thank you.

`New Term Label`
National Antimicrobial Resistance Monitoring System (NARMS)

**Parent Term**
antimicrobial resistance testing reference standard

**Definition**
The National Antimicrobial Resistance Monitoring System for Enteric Bacteria (NARMS) is a US public health surveillance system that tracks antimicrobial resistance in foodborne and other enteric bacteria.

**Definition Source**
[https://www.cdc.gov/narms/about/index.html#:~:text=The%20National%20Antimicrobial%20Resistance%20Monitoring,foodborne%20and%20other%20enteric%20bacteria]

**Term editor**
https://orcid.org/0000-0002-1107-9135

`New Term Label`
National Committee for Clinical Laboratory Standards (NCCLS)

**Parent Term**
antimicrobial resistance testing reference standard

**Definition**
The National Committee for Clinical Laboratory Standards is an American organization responsible for developing accredited consensus clinical laboratory standards.

**Term editor**
https://orcid.org/0000-0002-1107-9135

**Comment by smithk63** [comment]
Hello Anoosha,

Thanks for reaching out! The ARO is generally a collection of genetic elements and compounds (and associated data) related to antibiotic resistance, such as resistance genes/mutations, antibiotics, etc. So the ARO probably is not the best place for entries such as surveillance systems and organizations. However, these terms may be worth including in CARD. I can run the idea of a separate _Surveillance_ or _Standards_ ontology to the rest of the CARD team, but even if we do construct a new ontology for such terms, it is unlikely we will have anything ready for the next release.

Thank you,

Keaton Smith
Developer Assistant
CARD Junior Curator & Help Desk

**Comment by agmcarthur** [comment]
Hi Anoosha, looking closely we should be able to add these to the terminology branch of the ARO. We will look into this and get back to you shortly.

**Comment by Anoosha-Sehar** [comment]
Hi @agmcarthur Sure, that would be great. Thank you so much both of you for looking into it.

**Comment by smithk63** [comment]
Hey Anoosha,

Both these terms have been added to the terminology branch of the ARO. You should be able to view them after our update before the end of month.

Thanks!

**Comment by Anoosha-Sehar** [comment]
@smithk63 Hi Keaton, that sounds great. Thank you very much.

**Comment by agmcarthur** [comment]
Both are now live:
* National Antimicrobial Resistance Monitoring System (NARMS) https://card.mcmaster.ca/ontology/45935
* National Committee for Clinical Laboratory Standards (NCCLS) https://card.mcmaster.ca/ontology/45933
