### ISSUE TITLE
NTR: SIR & WRG

### ISSUE THREAD

**Issue by cmrn-rhi** [arpcard/aro#11]
### Parent Class: antimicrobial resistance testing reference standard [ARO:3004360]

**Label:** Swedish Reference Group for Antibiotics (SIR)
**Definition:** SIR is a revised system for antibiotic sensitivity testing in Sweden was proposed in 1977. The SIR system implied 2 main changes: 3 sensitivity groups instead of previous 4 and new breakpoints for the sensitivity groups. [[https://doi.org/10.3109/inf.1981.13.issue-2.13](https://doi.org/10.3109/inf.1981.13.issue-2.13)]

**Label:** Werkgroep Richtlijnen Gevoeligheidsbepalingen (WRG)
**Synonyms/Alternative Labels:** Working Group Guidelines Susceptibility Testing, Commissie Richtlijnen Gevoeligheidsbepalingen (CRG), Committee Guidelines Susceptibility Testing
**Definition:** WRG is a standardized antimicrobial susceptibility testing methodology created by the Dutch Commissie Richtlijnen Gevoeligheidsbepalingen in 1981. In these documents they have included species-specific regression lines clearly showing that these regression lines were different for different pathogens. [[https://doi.org/10.1007/bf01964289](https://doi.org/10.1007/bf01964289)]
**Synonym/Alternative labels source:** https://www.nvmm.nl/media/4409/152-157-degener.pdf

Requesting these ontology terms to assist in annotating historical (and theoretically current day) antimicrobial resistance testing datasets. This request is to support the Canadian Antimicrobial Resistance Genomics Research and Development Initiative (AMR-GRDI) specification being developed and maintained by the Centre for Infectious Disease Genomics and One Health (affiliated with FOODON & GENEPIO ontologies).

**Comment by cmrn-rhi** [comment]
Additional note: We are not attached to these definitions, I was just trying to assist in the curation process.

**Comment by agmcarthur** [comment]
Much thanks @cmrn-rhi. @arpcard I have curated these into the next version of the ARO. @cmrn-rhi this will be available upon the next public release.

**Comment by agmcarthur** [comment]
Resolved at CARD: https://card.mcmaster.ca/ontology/41533
