### ISSUE TITLE
NTR: BIOMIC Microbiology System

### ISSUE THREAD

**Issue by Anoosha-Sehar** [arpcard/aro#12]
Hi, I would like to request this term as a part of the Canadian Antimicrobial Resistance Genomics Research and Development Initiative (AMR-GRDI) project. 

Label: BIOMIC Microbiology System
Parent Class: automated testing platform [ARO:3004398]
Definition: Specific automated system of analysis for determining antimicrobial susceptibility developed by Giles Scientific.
Term editor: https://orcid.org/0000-0001-5275-8866

**Comment by agmcarthur** [comment]
Excellent, I will curate this now and it will be available in the next CARD Release. I will post here once the ontology term is public.

**Comment by agmcarthur** [comment]
The term will be ARO:3007569 once is public.

**Comment by Anoosha-Sehar** [comment]
@agmcarthur That's great. Thank you so much, Andrew!!

**Comment by agmcarthur** [comment]
@Anoosha-Sehar https://card.mcmaster.ca/ontology/46342!
