### ISSUE TITLE
Normalize PubChem compound references

### ISSUE THREAD

**Issue by agmcarthur** [arpcard/aro#7]
From @cthoyt 

> PubChem is an ambiguous prefix that could refer to one of the several semantic spaces. 

@arpcard in ARO.owl and ARO.obo please replace `PubChem:` with `pubchem.compound:`

For example:

> PubChem:5284517
>
>pubchem.compound:5284517

**Comment by raphenya** [comment]
This is now updated to use `pubchem.compound`.
