### ISSUE TITLE
Improve documentation for external contributors

### ISSUE THREAD

**Issue by cthoyt** [arpcard/aro#9]
In https://github.com/arpcard/aro/pull/6#issuecomment-1168893665, @agmcarthur noted that ARO is only updated via the CARD website (a curation interface), which conflicts with the documentation on the README saying that there's an editors file

https://github.com/arpcard/aro/blob/37b49751c61d3be0b0096b3e10ac10e5e4a5aa82/README.md?plain=1#L19-L21

Would you please clarify on the README (and ideally, with a CONTRIBUTING.md file) if and how how external contributions can be made to this ontology?

**Comment by agmcarthur** [comment]
Will do @cthoyt. Ping @arpcard team.

**Comment by raphenya** [comment]
added CONTRIBUTING file.
